# Generated by Django 4.2.7 on 2025-01-30 18:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lesseon',
            new_name='Lesson',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='dictionary',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-created']},
        ),
    ]
