# Generated by Django 4.2.7 on 2025-01-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_lesseon_lesson_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
