# Generated by Django 4.2.7 on 2025-02-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
