# Generated by Django 4.2.7 on 2025-01-31 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_dictionary_language_alter_dictionary_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='title',
        ),
    ]
